import os
import json


# get project config generated by codeseed
def get_project_config():
    json_file_path = ".codeseed.json"
    current_path = os.getcwd()
    current_path_array = current_path.split("/")
    new_path = ""

    for i in range(len( current_path_array )):
        new_path = "/".join(current_path_array)
        codeseed_path = new_path + "/" + json_file_path
        if os.path.exists(codeseed_path):
            with open(codeseed_path, 'r') as file:
                config = json.load(file)
            return config
        current_path_array.pop()
    return False

# create files for every layer
def create_files(project_root, filename, project_language):
    layer_paths = [
        "/src/controller",
        "/src/repository",
        "/src/interfaces/interactor"
    ]
    for path in layer_paths:
        basename = os.path.basename(path)
        base_path = project_root + path + "/" 

        if os.path.exists(base_path) != True:
            return base_path

        if project_language == "golang":
            new_layer_path = base_path + filename + "_" + basename + ".go"
            if os.path.exists(new_layer_path):
                return new_layer_path
            print("CREATING: " + new_layer_path)
        else:
            new_layer_path =  base_path + filename + basename.capitalize() + ".ts"
            if os.path.exists(new_layer_path):
                return new_layer_path
            print("CREATING: " + new_layer_path)
        with open(new_layer_path, "w"):
            pass
    return "DONE"
