import os
import json

from utils import pathmaker
from utils import templates

# get project config generated by codeseed
def get_project_config(file_separator):
    json_file_path = ".codeseed.json"
    current_path = os.getcwd()
    current_path_array = current_path.split(file_separator)

    # find .codeseed.json
    for i in range(len( current_path_array )):
        new_path = file_separator.join(current_path_array)
        codeseed_path = new_path + file_separator + json_file_path
        if os.path.exists(codeseed_path):
            with open(codeseed_path, 'r') as file:
                config = json.load(file)
            return config
        current_path_array.pop()
    return False

# bare-minimum layer content for golang — struct + constructor + empty
# interface. Method bodies are project-specific, left for the user to fill
# in; the inputport files carry a go:generate mockgen directive (matching
# go.uber.org/mock) so a mock is one `go generate ./...` away once the
# interface actually has methods on it.
def _golang_layer_targets(project_root, filename, file_separator):
    module = os.path.basename(project_root.rstrip(file_separator))
    type_name = filename.capitalize()
    var_name = filename

    base = project_root + file_separator + "internal" + file_separator

    return [
        {
            "path": base + "domain" + file_separator + "entities" + file_separator + filename + ".go",
            "package": "entities",
            "template": "golang/entity.go.tmpl",
            "vars": {"type_name": type_name},
        },
        {
            "path": base + "domain" + file_separator + "interactor" + file_separator + "inputport" + file_separator + filename + "_interactor_inputport.go",
            "package": "inputport",
            "template": "golang/interactor_inputport.go.tmpl",
            "vars": {"type_name": type_name},
        },
        {
            "path": base + "domain" + file_separator + "interactor" + file_separator + filename + "_interactor.go",
            "package": "interactor",
            "template": "golang/interactor.go.tmpl",
            "vars": {"module": module, "type_name": type_name, "var_name": var_name},
        },
        {
            "path": base + "domain" + file_separator + "repository" + file_separator + "inputport" + file_separator + filename + "_repository_inputport.go",
            "package": "inputport",
            "template": "golang/repository_inputport.go.tmpl",
            "vars": {"type_name": type_name},
        },
        {
            "path": base + "domain" + file_separator + "repository" + file_separator + filename + "_repository.go",
            "package": "repository",
            "template": "golang/repository.go.tmpl",
            "vars": {"type_name": type_name},
        },
        {
            "path": base + "controller" + file_separator + filename + "_controller.go",
            "package": "controller",
            "template": "golang/controller.go.tmpl",
            "vars": {"module": module, "type_name": type_name, "var_name": var_name},
        },
    ]


def _create_golang_files(project_root, filename, file_separator, with_test):
    for target in _golang_layer_targets(project_root, filename, file_separator):
        parent = os.path.dirname(target["path"])
        if os.path.exists(parent) != True:
            return parent

        if os.path.exists(target["path"]):
            return target["path"]

        print("CREATING: " + target["path"])
        with open(target["path"], "w") as f:
            f.write(templates.render(target["template"], **target["vars"]))

        if with_test:
            test_path = target["path"][:-3] + "_test.go"
            print("CREATING: " + test_path)
            with open(test_path, "w") as f:
                f.write("package " + target["package"] + "\n")

    return "DONE"


# create files for every layer
def create_files(project_root, filename, project_language, file_separator, with_test):
    # TODO: run create_path only when on windows system
    if project_language == "golang":
        return _create_golang_files(project_root, filename, file_separator, with_test)

    layer_paths = pathmaker.create_path([
        "/src/controller",
        "/src/repository",
        "/src/interfaces/interactor"
    ],file_separator)

    for path in layer_paths:
        basename = os.path.basename(path)
        base_path = project_root + path + file_separator

        if os.path.exists(base_path) != True:
            return base_path

        new_layer_path = base_path + filename + basename.capitalize() + ".ts"
        if with_test:
            test_layer_path = base_path + filename + basename.capitalize() + "Test.ts"

        if os.path.exists(new_layer_path):
            return new_layer_path

        print("CREATING: " + new_layer_path)
        with open(new_layer_path, "w"):
            pass

        if with_test:
            print("CREATING: " + test_layer_path)
            with open(test_layer_path, "w"):
                pass
    return "DONE"
