FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app/bin/${foldername} ./cmd/${foldername}

FROM alpine:latest
WORKDIR /app
COPY --from=build /app/bin/${foldername} ./${foldername}
EXPOSE 8080
ENTRYPOINT ["./${foldername}"]
